### PR TITLE
Fix Rust symbols in collapse-dtrace and collapse-perf

### LINKED ISSUE #87: Add back demangling support
Prior to #74, we had support for demangling function names (although only with `--inline`). While perf is _supposed_ to be doing it already (see [`--demangle`](http://man7.org/linux/man-pages/man1/perf-script.1.html)) there are [reports](https://www.reddit.com/r/rust/comments/b08oex/cargoflamegraph_generate_flame_graphs_directly/eidhhz8/) that it doesn't demangle everything super well. Having our own demangling step using one of the [many demangling crates](https://crates.io/search?q=demangle&sort=recent-downloads) seems like it might be a good idea!

### PR DESCRIPTION
**Pull request by jasonrhansen**
This fixes partially demangled Rust function names like we did with collapse-sample.

#132 was already meant to fix #87, but it required `dtrace` to be run with `-xmangled` to leave the names mangled. You then had to pass `--demangle` to `inferno-collapse-dtrace`. This PR will give good results for Rust symbols with the default options.

### CODE REVIEW

**Comment by jasonrhansen** [comment]
I did the same for `collapse-perf`. When I run `perf` on my machine, the Rust names are mostly demangled correctly, with the only exception I can see being closures. However, the Rust test profiles from upstream flamegraph have symbols that look like the partially demangled symbols from `dtrace` or `sample`. I'm guessing older versions of `perf` didn't demangle Rust as well?

File: src/collapse/dtrace.rs [hunk 1]
```diff
@@ -168,26 +169,39 @@ impl Folder {
...
                 if let (Some(offset), Some(func)) = (parts.next(), parts.next()) {
-                    return Cow::Owned(format!(
-                        "{}`{}+{}",
-                        pname,
-                        symbolic_demangle::demangle(func),
-                        offset
-                    ));
+                    if let Cow::Owned(func) = transform(func.trim_end()) {
+                        return Cow::Owned(format!("{}`{}+{}", pname, func, offset));
+                    }
```
Comment (jonhoo) [inline src/collapse/dtrace.rs]: I think this is missing an `else` so we don't double-evaluate `transform` with the `if let` below.
