### PR TITLE
Filter out lines which begin with '# ' in inferno-flamegraph

### LINKED ISSUE #238: flamegraph panics on empty lines with --reverse set
Found while I was investigating #237 

Repro:
* Change `tests/data/flamegraph/bad-lines/bad-lines.txt` to the following (adding a blank line):
```
cksum;_start;__libc_start_main;main;cksum 31
cksum;cksum 6
THIS IS A BAD LINE
cksum;cksum;__GI___fread_unlocked;_IO_file_xsgetn;_IO_file_read;entry_SYSCALL_64_fastpath_[k];sys_read_[k];vfs_read_[k];__vfs_read_[k];ext4_file_read_iter_[k] 1
cksum;main;cksum 19
THIS IS A BAD FRACTIONAL LINE 12V.43
noploop;[unknown] 2
noploop;main 274

noploop;[unknown] 2
```
* Run `cargo test flamegraph_should_warn_about_bad_input_lines_with_reversed_stack_ordering`

Failure:
```
---- flamegraph_should_warn_about_bad_input_lines_with_reversed_stack_ordering stdout ----
thread 'flamegraph_should_warn_about_bad_input_lines_with_reversed_stack_ordering' panicked at 'attempt to subtract with overflow', /home/mike/inferno/src/flamegraph/mod.rs:415:60
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    flamegraph_should_warn_about_bad_input_lines_with_reversed_stack_ordering
```

The issue is here: https://github.com/jonhoo/inferno/blob/master/src/flamegraph/mod.rs#L411

`samples_idx` is 0 when we have an empty line, and we are trying to subtract from it.

A simple fix would be to add a check for `line.is_empty()` at the top of that loop. Alternatively, it seems like the reason we are subtracting 1 from sample_idx is to remove a trailing space from the line, so replacing with `&line[..samples_idx].trim_end()` would fix it.

### PR DESCRIPTION
**Pull request by mrob95**
implements #237 

also fixes #238 by moving the check for empty/ignored lines out of `merge` and into `from_lines`. I think this makes more sense as the block in `from_lines` which handles `opt.reverse_stack_order` pre-processes the samples before calling `merge`, and seems to assume that the lines it deals with are not empty. I'm not very experienced with rust though, so please let me know if there is a better way!

I've added an empty line to the `bad-lines` test file as a regression test for #238, and a couple of test files for input from the austin profiler.

### CODE REVIEW

File: src/flamegraph/mod.rs [hunk 1]
```diff
@@ -394,6 +394,8 @@ where
     W: Write,
 {
     let mut reversed = StrStack::new();
+    let lines = lines.into_iter().filter(|line| !(line.is_empty() || line.starts_with("# ")));
```
Comment (jonhoo) [inline src/flamegraph/mod.rs:397]: I think this is missing a `.trim()` call. Without that, a line that's empty except for spaces would not get skipped whereas it does today.

**Review by jonhoo — CHANGES_REQUESTED** [review]
Just one small nit and then I think we're good to land this. Thanks for taking the time to fix the issue too!

File: src/flamegraph/mod.rs (hunk 1 above)
Comment (mrob95) [reply src/flamegraph/mod.rs]: Ah yes, fixed :)

**Review by jonhoo — APPROVED** [review]

**Comment by jonhoo** [comment]
Thanks! I'll fix the MSRV issue separately — that's not caused by your change.

**Comment by jonhoo** [comment]
Published as 0.11.3 :tada:

**Comment by mrob95** [comment]
Awesome! Thanks 😊
